image: docker:latest
services:
- docker:18.06.0-dind

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_URL: registry.gitlab.com
  CONTAINER_PATH: /vibent/vibent-ui
  CONTAINER_IMAGE: ${CONTAINER_URL}${CONTAINER_PATH}

stages:
- build
- dockerize
- deploy

build:
  stage: build
  image: node:8.11.3
  script:
  - apt update
  - apt install -q jq
  - echo "VERSION=$(jq -r ".version" ./package.json)" > env.sh
  - npm install
  - npm rebuild node-sass
  - npm run build-prod
  artifacts:
    paths:
    - dist
    - env.sh

dockerize:
  stage: dockerize
  only:
  - develop
  when: manual
  allow_failure: false
  script:
  - source env.sh
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_URL
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$VERSION --tag $CONTAINER_IMAGE:latest .
  - docker push $CONTAINER_IMAGE:$VERSION
  - docker push $CONTAINER_IMAGE:latest
  dependencies:
  - build

deploy:
  stage: deploy
  only:
  - develop
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -X POST -d "{\"token\":\"$AWS_UTIL_TOKEN\",\"restart\":\"vibent-ui\"}" https://admin.dev.vibent.com
